# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Print a joint distribution
#'
#' The function prints the distribution specification C++ funcitons received
#'
#' @name print_prior
#' @param p_prior_r A List containing prior distribution specifications.
#'
#' @return
#' \describe{Character vector describing the prior distribution}
#'
#' @details
#' These functions provide the core computational methods for prior
#' distributions:
#'  \itemize{
#'   \item `print_prior`: Returns a textual description of the prior
#'         specification
#' }
#'
#' The prior specification (`p_prior_r`) should be a List with elements
#' from the \code{BuildPrior}.
#'
#' @examples
#' p0 <- c(A = 0.15, B = 0.45, mean_v = 2.25, sd_v = 0.15, t0 = 0.2)
#' p1 <- rep(0.1, 5)
#' p_prior <- BuildPrior(
#'     p0 = p0,
#'     p1 = p1,
#'     lower = rep(NA, 5),
#'     upper = rep(NA, 5),
#'     dist = rep("tnorm", 5),
#'     log_p = rep(TRUE, 5)
#' )
#' pnames <- print_prior(p_prior)
#'
#' @export
print_prior <- function(p_prior_r) {
    .Call('_ggdmcPrior_print_prior', PACKAGE = 'ggdmcPrior', p_prior_r)
}

#' Density and random number generation
#'
#' \code{dprior} computes the density for a joint distribution. \code{rprior}
#' generates random numbers based on the specification in the \code{p_prior_r}
#'
#' @param p_prior_r A List containing distribution specifications (usually
#' specified in \code{BuildPrior} function).
#' @param parameters_r For `dprior`: A NumericVector of parameter values at
#'        which to evaluate the prior density.
#' @param n For `rprior`: Number of random samples to generate (default = 1).
#'
#' @return
#' \describe{
#'   \item{`dprior`}{an R vector of prior density values}
#'   \item{`rprior`}{an R matrix of random samples (n rows × parameters
#'               columns)}
#'  }
#'
#' @details
#' These functions provide the core computational methods for prior
#' distributions:
#'  \itemize{
#'   \item `dprior`: Evaluates the prior probability density function
#'   \item `rprior`: Generates random samples from the prior distribution
#' }
#'
#' @examples
#' p0 <- c(A = 0.15, B = 0.45, mean_v = 2.25, sd_v = 0.15, t0 = 0.2)
#' p1 <- rep(0.1, 5)
#' p_prior <- BuildPrior(
#'     p0 = p0,
#'     p1 = p1,
#'     lower = rep(NA, 5),
#'     upper = rep(NA, 5),
#'     dist = rep("tnorm", 5),
#'     log_p = rep(TRUE, 5)
#' )
#'
#' # Test dprior -----------------
#' parameters <- seq(0.1, 0.5, 0.1)
#' res0 <- dprior(p_prior, parameters)
#' res1 <- dnorm(parameters, p0, 0.1, TRUE)
#' print(res0)
#' print(res1)
#'
#' # Test rprior -----------------
#' res2 <- rprior(p_prior, 1)
#' print(res2)
#' res3 <- rprior(p_prior, 2)
#' print(res3)
#' @export
dprior <- function(p_prior_r, parameters_r) {
    .Call('_ggdmcPrior_dprior', PACKAGE = 'ggdmcPrior', p_prior_r, parameters_r)
}

#' @rdname dprior
#' @export
rprior <- function(p_prior_r, n = 1L) {
    .Call('_ggdmcPrior_rprior', PACKAGE = 'ggdmcPrior', p_prior_r, n)
}

#' Sum of joint densities
#'
#' Computes the sum of joint densities for a vector of parameters given
#' the distribution specification. The function computes log densities
#' only when the \code{log_p} is set to TRUE. This function can be
#' used in Bayesian computations where the joint prior is the product
#' of independent priors (sum in log-space).
#'
#' @param p_prior_r A List of prior specifications, where each element is
#'                  itself a List containing the distribution details
#'                  for one parameter. Each sublist should contain:
#'   \itemize{
#'      \item \code{p0}: The first parameter of the distribution.
#'      \item \code{p1}: The second parameter of the distribution.
#'      \item \code{lower}: The lower bound of the distribution.
#'      \item \code{upper}: The upper bound of the distribution.
#'      \item \code{dist}: A numeric code representing the distribution type.
#'      \item \code{log_p}: Logical indicating whether probabilities
#'                          are logged.
#'    }
#' @param parameters_r A NumericVector of parameter values at which to
#'                     evaluate the densities. The length should match
#'                     the length of \code{p_prior_r}.
#'
#' @return A single double value representing the sum of log-prior densities:
#'         \deqn{\sum_{i=1}^{k} \log p(\theta_i | \text{prior}_i)}
#'         where \eqn{k} is the number of parameters.
#'
#' @details
#' This function:
#' \itemize{
#'   \item Iterates through each parameter and its prior specification
#'   \item Computes the log-density for each parameter value
#'   \item Sums all log-density values
#'   \item Returns the total sum (useful for log-posterior computation)
#' }
#'
#'
#' @examples
#' p0 <- c(A = 0.15, B = 0.45, mean_v = 2.25, sd_v = 0.15, t0 = 0.2)
#' tnorm_prior <- BuildPrior(
#'     p0 = p0,
#'     p1 = rep(1, 5),
#'     lower = rep(0, 5),
#'     upper = rep(NA, 5),
#'     dist = rep("tnorm", 5),
#'     log_p = rep(TRUE, 5)
#' )
#'
#' npar <- length(tnorm_prior)
#' result <- sumlogprior(p_prior_r = tnorm_prior,
#'                       parameters_r = runif(npar, 0, 10))
#' @export
sumlogprior <- function(p_prior_r, parameters_r) {
    .Call('_ggdmcPrior_sumlogprior', PACKAGE = 'ggdmcPrior', p_prior_r, parameters_r)
}

#' Truncated normal distribution
#'
#' Density, distribution function, and random generation for the truncated
#' normal distribution with mean `p0`, standard deviation `p1`, and bounds
#' [`lower`, `upper`].
#'
#' @name tnorm
#' @aliases rtnorm ptnorm dtnorm
#' @param n Number of random variates to generate (for `rtnorm`).
#' @param x Vector of quantiles (for `dtnorm` and `ptnorm`).
#' @param p0 Mean of the underlying normal distribution.
#' @param p1 Standard deviation of the underlying normal distribution.
#' @param lower Lower truncation bound.
#' @param upper Upper truncation bound.
#' @param lower_tail Logical; if TRUE (default), probabilities are
#'         \deqn{P[X \leq x]}, otherwise P[X > x].
#' @param log_p Logical; if TRUE, probabilities/densities p are returned as
#' log(p).
#'
#' @return
#' \describe{
#'   \item{`rtnorm`}{NumericVector of random variates from the truncated
#'          normal}
#'  \item{`ptnorm`}{NumericVector of cumulative probabilities}
#'  \item{`dtnorm`}{NumericVector of density values}
#' }
#'
#'  @details
#'  These functions implement the truncated normal distribution:
#'  \itemize{
#'    \item `rtnorm`: Random number generation using inverse transform sampling
#'    \item `ptnorm`: Cumulative distribution function (CDF)
#'    \item `dtnorm`: Probability density function (PDF)
#'  }
#'
#' The distribution is defined as:
#' \deqn{X \sim \mathcal{N}(\mu, \sigma^2), \text{truncated to } [a, b]}
#' where \eqn{\mu = p0}, \eqn{\sigma = p1}, \eqn{a = lower}, \eqn{b = upper}.
#'
#' @references
#' \itemize{
#'   \item RcppTN package by Jonathan Olmsted (RcppTN 0.1-8)
#'         \url{https://github.com/olmjo/RcppTN}
#'   \item msm package by Christopher Jackson
#'         \url{https://cran.r-project.org/package=msm}
#'   \item Robert, C.P. (1995). "Simulation of truncated normal variables".
#'     Statistics and Computing, 5(2), 121-125. \doi{10.1007/BF00143942}
#'  }
#'
#' @examples
#' n <- 1e5
#' p0 <- 0
#' p1 <- 1
#' lower <- 0
#' upper <- Inf
#' rtnorm_dat <- rtnorm(n, p0, p1, lower, upper)
#'
#' ## dtnorm example
#' x <- seq(-5, 5, length.out = 1e3)
#' dtnorm_dat <- dtnorm(x, p0, p1, lower = -2, upper = 2, log_p = FALSE)
#' q <- seq(-5, 5, length.out = 1e3)
#'
#' ptnorm_dat <- ptnorm(q, p0, p1, lower = -2, upper = 3, lower_tail = TRUE,
#'                  log_p = FALSE)
#'
#' cex_lab <- 1
#' cex_axis <- 0.5
#' line_width <- 1.5
#'
#' hist(rtnorm_dat, breaks = "fd", freq = FALSE, xlab = "", cex.lab = cex_lab,
#' cex.axis = cex_axis, main = "" )
#' plot(x, dtnorm_dat, type = "l", lwd = line_width, xlab = "",
#' ylab = "Density", cex.lab = cex_lab, cex.axis = cex_axis, main = "")
#'
#' @export
rtnorm <- function(n, p0, p1, lower, upper) {
    .Call('_ggdmcPrior_rtnorm', PACKAGE = 'ggdmcPrior', n, p0, p1, lower, upper)
}

#' @rdname tnorm
#' @export
ptnorm <- function(x, p0, p1, lower, upper, lower_tail, log_p = FALSE) {
    .Call('_ggdmcPrior_ptnorm', PACKAGE = 'ggdmcPrior', x, p0, p1, lower, upper, lower_tail, log_p)
}

#' @rdname tnorm
#' @export
dtnorm <- function(x, p0, p1, lower, upper, log_p = FALSE) {
    .Call('_ggdmcPrior_dtnorm', PACKAGE = 'ggdmcPrior', x, p0, p1, lower, upper, log_p)
}

